name: "Basic_Workflow"

on:
  push:
    branches:
    - 'main'
    - 'feature/**'

jobs:
  first_job:
    name: first_job
    runs-on: githubshine 
    steps:
      - name: print the shine
        run: echo shine

    


  
